wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1656406459
    t:
      1:
      - 1
      - 5
      - 11
      - 40
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      4: 3.10.4
      5: 0.12.19
      6: 4.18.0
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 64
embedding_length:
  desc: null
  value: 128
epochs:
  desc: null
  value: 30
hidden_size:
  desc: null
  value: 1024
lr:
  desc: null
  value: 0.0001
name:
  desc: null
  value: aes
num_attention_heads:
  desc: null
  value: 8
num_encoder_layers:
  desc: null
  value: 6
num_regression_layers:
  desc: null
  value: 0
r2_coeff:
  desc: null
  value: 0.0007
regression_size:
  desc: null
  value: 512
stdev_coeff:
  desc: null
  value: 0.6
stdev_start:
  desc: null
  value: 0.2
stdev_start_coeff:
  desc: null
  value: 1.0
